# Generated by Django 5.0.3 on 2024-03-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_scan_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectBlank',
            new_name='ImageFile',
        ),
    ]
