# Generated by Django 5.0.3 on 2024-03-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_scan_app', '0003_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='disease',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='signal',
            name='health',
            field=models.FloatField(),
        ),
    ]
