# Generated by Django 5.0.3 on 2024-03-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_scan_app', '0004_alter_signal_disease_alter_signal_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-30 12:05:43.576740'),
            preserve_default=False,
        ),
    ]
