# Generated by Django 4.1.4 on 2023-05-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="faculty_number",
        ),
    ]
